#Description:
# 代价地图通用参数配置文件,就是全局代价地图和局部代价地图
# 共同都需要配置的参数,各参数意义如下:
# robot_radius: 机器人的半径
# "obstacle_range" 参数确定最大范围传感器读数，这将导致障碍物被放入代价地图中。
# 在这里，我们把它设置在3米，这意味着机器人只会更新其地图包含距离移动基座3米以内的障碍物的信息。
# “raytrace_range”参数确定了用于清除指定范围外的空间。
# 将其设置为3.0米，这意味着机器人将尝试清除3米外的空间，在代价地图中清除3米外的障碍物。

#robot_radius: 0.2

footprint: [[0.171, -0.128], [0.171, 0.128],[-0.171, 0.128], [-0.171, -0.128]]

obstacle_layer:
  enabled: true
  combination_method: 1
  track_unknown_space: true
  obstacle_range: 2.0
  raytrace_range: 2.0
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {
    sensor_frame: laser_frame,
    data_type: LaserScan,
    topic: scan,
    marking: true,
    clearing: true,
    inf_is_valid: true
  }
 
inflation_layer:
  enabled: true
  cost_scaling_factor: 5.0
  inflation_radius: 0.3
#0.15
 
static_layer:
  enabled: true
